/**
 * The revocation proceeding vocabulary. Isomorphic.
 *
 *   ZJD (or whoever the workflow names): Initiate ─▶ PROPOSED
 *   Revoking authority: Take up ──────────────────▶ UNDER_REVIEW
 *   Revoking authority: Decide ───────────────────▶ REVOKED  │ REJECTED
 *
 * Every one of those moves is a WORKFLOW transition out of the approved
 * terminal stage (see prisma/seed/workflow/bbas-standard.ts), so which role
 * initiates and which decides is configuration.
 *
 * ── What REVOKED does, and what it does not ──────────────────────────────
 *
 * It moves the application to the terminal stage CLOSED_REVOKED, whose status
 * is PROCEEDING_REVOKED; it marks the approval order revoked; and it generates
 * a revocation order that is sent to the Outward register. It deletes NOTHING:
 * the approval transition, the approval date, the approval order and its
 * snapshot all remain exactly as they were, and the file's history reads
 * "Approved … then revoked", in that order.
 */

export const REVOCATION_STATUSES = ['PROPOSED', 'UNDER_REVIEW', 'REVOKED', 'REJECTED'] as const;
export type RevocationStatus = (typeof REVOCATION_STATUSES)[number];

export const REVOCATION_STATUS_LABEL: Record<RevocationStatus, string> = {
  PROPOSED: 'Proposed',
  UNDER_REVIEW: 'Under review',
  REVOKED: 'Revoked',
  REJECTED: 'Rejected',
};

export const isRevocationStatus = (v: string): v is RevocationStatus =>
  (REVOCATION_STATUSES as readonly string[]).includes(v);

export const OPEN_REVOCATION_STATUSES: readonly RevocationStatus[] = ['PROPOSED', 'UNDER_REVIEW'];

export const isRevocationOpen = (status: string) => (OPEN_REVOCATION_STATUSES as readonly string[]).includes(status);

export const REVOCATION_DECISIONS = ['REVOKED', 'REJECTED'] as const;
export type RevocationDecision = (typeof REVOCATION_DECISIONS)[number];

export const REVOCATION_DECISION_LABEL: Record<RevocationDecision, string> = {
  REVOKED: 'Revoke the permission',
  REJECTED: 'Reject the proposal',
};

/** The status an application takes when its permission is revoked. */
export const PROCEEDING_REVOKED = 'PROCEEDING_REVOKED';

export const DEMO_ORDER_NOTE =
  'DEMO DOCUMENT — generated by the Nirman demonstration. Not an order made under any law.';
