import 'server-only';
import type { Prisma } from '@prisma/client';
import { prisma } from '@/server/db/prisma';
import { applicationScope } from '@/server/auth/scope';
import { can, type AuthUser } from '@/server/auth/context';
import { badRequest, conflict, forbidden, notFound } from '@/server/http/errors';
import { isUuid } from '@/lib/utils';
import { CAPABILITIES } from '@/lib/constants';
import {
  OUTWARD_ACTION_LABEL,
  OUTWARD_ACTION_RESULT,
  OUTWARD_STATUS_LABEL,
  SYSTEM_GENERATED_TYPES,
  canMoveOutward,
  deliveryStatusLabel,
  isOutwardDocumentType,
  isOutwardStatus,
  outwardMoves,
  type OutwardAction,
  type OutwardStatus,
} from '@/lib/outward';
import type { CreateOutwardInput, OutwardActionInput } from '@/lib/schemas/proceedings';
import { createOutwardEntry } from '@/server/proceedings/engine';
import { renderOutwardCover } from '@/server/proceedings/documents';
import { audit } from './audit';
import { readShowCauseNotice } from './show-cause';
import { readRevocationOrder } from './revocations';

/**
 * THE OUTWARD REGISTER.
 *
 * Clerical: it records that a document left the office, how, and what became
 * of it. It never moves an application. Show cause notices and revocation
 * orders arrive here on their own, created in the transaction that generated
 * them; everything else is entered by hand.
 *
 * One cross-module consequence, and only one: dispatching a show cause notice
 * starts its response window — the notice moves from ISSUED to
 * AWAITING_RESPONSE, because an applicant cannot answer a notice that has not
 * been sent.
 */

type Meta = { ip: string; userAgent: string; correlationId?: string };
const TX_LIMITS = { timeout: 20_000, maxWait: 10_000 } as const;

/** A notice or order generated by its module is dispatched, never cancelled here. */
const GENERATED_SOURCES = ['ShowCauseNotice', 'RevocationProceeding', 'DeveloperRegistration', 'ProfessionalRegistration'];

const APP_SELECT = {
  id: true,
  applicationNumber: true,
  applicant: { select: { name: true, ownerName: true } },
} satisfies Prisma.ApplicationSelect;

function requireView(user: AuthUser) {
  if (!can(user, CAPABILITIES.OUTWARD_VIEW)) throw forbidden('Your role does not include the Outward register.');
}
function requireManage(user: AuthUser) {
  if (!can(user, CAPABILITIES.OUTWARD_MANAGE)) throw forbidden('Your role does not keep the Outward register.');
}

/** Entries for files in scope, plus entries that belong to no file. */
const scopeWhere = (user: AuthUser): Prisma.OutwardEntryWhereInput => ({
  OR: [{ applicationId: null }, { application: { deletedAt: null, ...applicationScope(user) } }],
});

async function requireEntry(user: AuthUser, id: string) {
  if (!isUuid(id)) throw notFound('That outward entry could not be found.');
  const row = await prisma.outwardEntry.findFirst({
    where: { id, ...scopeWhere(user) },
    include: { application: { select: APP_SELECT } },
  });
  if (!row) throw notFound('That outward entry could not be found.');
  return row;
}

const owner = (a: { applicant: { name: string | null; ownerName: string } | null } | null) =>
  a?.applicant?.ownerName?.trim() || a?.applicant?.name?.trim() || '';

/** Links the register can follow back to the document's own record. */
function sourceLink(sourceType: string, sourceId: string): string {
  if (sourceType === 'ShowCauseNotice') return `/show-cause/${sourceId}`;
  if (sourceType === 'RevocationProceeding') return `/revocations/${sourceId}`;
  if (sourceType === 'DeveloperRegistration') return `/developers/${sourceId}`;
  if (sourceType === 'ProfessionalRegistration') return `/professionals/${sourceId}`;
  return '';
}

// ═══════════════════════════════════════════════════════════════════════════
// The register
// ═══════════════════════════════════════════════════════════════════════════

export type OutwardListQuery = {
  q?: string;
  status?: string;
  documentType?: string;
  applicationId?: string;
  page?: number;
  pageSize?: number;
};

export async function listOutward(user: AuthUser, query: OutwardListQuery = {}) {
  requireView(user);
  const and: Prisma.OutwardEntryWhereInput[] = [scopeWhere(user)];
  if (query.status === 'PENDING') and.push({ status: { in: ['DRAFT', 'READY_FOR_DISPATCH'] } });
  else if (query.status && isOutwardStatus(query.status)) and.push({ status: query.status });
  if (query.documentType && isOutwardDocumentType(query.documentType)) and.push({ documentType: query.documentType });
  if (query.applicationId && isUuid(query.applicationId)) and.push({ applicationId: query.applicationId });
  const q = query.q?.trim();
  if (q) {
    and.push({
      OR: [
        { outwardNumber: { contains: q, mode: 'insensitive' } },
        { documentReference: { contains: q, mode: 'insensitive' } },
        { recipient: { contains: q, mode: 'insensitive' } },
        { trackingNumber: { contains: q, mode: 'insensitive' } },
        { application: { applicationNumber: { contains: q, mode: 'insensitive' } } },
      ],
    });
  }
  const where = { AND: and };
  const page = Math.max(1, Math.trunc(query.page ?? 1));
  const pageSize = Math.min(100, Math.max(5, Math.trunc(query.pageSize ?? 20)));
  const [total, rows] = await Promise.all([
    prisma.outwardEntry.count({ where }),
    prisma.outwardEntry.findMany({
      where,
      orderBy: [{ assignedDate: 'desc' }, { outwardNumber: 'desc' }],
      skip: (page - 1) * pageSize,
      take: pageSize,
      include: { application: { select: APP_SELECT } },
    }),
  ]);
  return {
    page,
    pageSize,
    total,
    totalPages: Math.max(1, Math.ceil(total / pageSize)),
    rows: rows.map(({ application, ...r }) => ({
      id: r.id,
      outwardNumber: r.outwardNumber,
      documentType: r.documentType,
      documentReference: r.documentReference,
      recipient: r.recipient,
      address: r.address,
      assignedDate: r.assignedDate,
      dispatchDate: r.dispatchDate,
      mode: r.mode,
      trackingNumber: r.trackingNumber,
      status: r.status,
      deliveryStatus: deliveryStatusLabel(r.status),
      acknowledgement: r.acknowledgement,
      acknowledgementDate: r.acknowledgementDate,
      application: application ? { id: application.id, applicationNumber: application.applicationNumber, owner: owner(application) } : null,
    })),
  };
}

export async function outwardSummary(user: AuthUser) {
  requireView(user);
  const byStatus = await prisma.outwardEntry.groupBy({ by: ['status'], where: scopeWhere(user), _count: { _all: true } });
  const s = Object.fromEntries(byStatus.map((g) => [g.status, g._count._all])) as Record<string, number>;
  const get = (k: OutwardStatus) => s[k] ?? 0;
  return {
    total: Object.values(s).reduce((a, b) => a + b, 0),
    pending: get('DRAFT') + get('READY_FOR_DISPATCH'),
    ready: get('READY_FOR_DISPATCH'),
    inTransit: get('DISPATCHED'),
    delivered: get('DELIVERED') + get('ACKNOWLEDGED'),
    acknowledged: get('ACKNOWLEDGED'),
    returned: get('RETURNED'),
  };
}

// ═══════════════════════════════════════════════════════════════════════════
// One entry
// ═══════════════════════════════════════════════════════════════════════════

export async function getOutward(user: AuthUser, id: string) {
  requireView(user);
  const row = await requireEntry(user, id);
  const events = await prisma.outwardEvent.findMany({ where: { outwardId: row.id }, orderBy: { occurredAt: 'desc' } });
  const { application, ...rest } = row;
  return {
    ...rest,
    deliveryStatus: deliveryStatusLabel(row.status),
    sourceLink: sourceLink(row.sourceType, row.sourceId),
    application: application ? { id: application.id, applicationNumber: application.applicationNumber, owner: owner(application) } : null,
    events,
    permissions: {
      moves: can(user, CAPABILITIES.OUTWARD_MANAGE)
        ? outwardMoves(row.status).filter((m) => !(m === 'CANCEL' && GENERATED_SOURCES.includes(row.sourceType)))
        : [],
    },
  };
}

// ═══════════════════════════════════════════════════════════════════════════
// Create — by hand
// ═══════════════════════════════════════════════════════════════════════════

export async function createOutward(user: AuthUser, input: CreateOutwardInput, meta: Meta) {
  requireView(user);
  requireManage(user);
  if ((SYSTEM_GENERATED_TYPES as readonly string[]).includes(input.documentType)) {
    throw badRequest('Show cause notices and revocation orders are sent to Outward automatically when they are generated.', [
      { path: 'documentType', message: 'Choose another document type.' },
    ]);
  }

  let app: {
    id: string;
    applicationNumber: string;
    applicant: { name: string | null; ownerName: string; address: string; ownerAddress: string } | null;
    approvalOrder: { orderNumber: string } | null;
  } | null = null;
  const ref = input.application.trim();
  if (ref) {
    app = await prisma.application.findFirst({
      where: {
        deletedAt: null,
        ...applicationScope(user),
        ...(isUuid(ref) ? { id: ref } : { applicationNumber: { equals: ref, mode: 'insensitive' } }),
      },
      select: {
        id: true,
        applicationNumber: true,
        applicant: { select: { name: true, ownerName: true, address: true, ownerAddress: true } },
        approvalOrder: { select: { orderNumber: true } },
      },
    });
    if (!app) throw badRequest('That application could not be found.', [{ path: 'application', message: 'Check the application number.' }]);
  } else if (input.documentType !== 'OTHER') {
    throw badRequest('Name the application this document belongs to.', [{ path: 'application', message: 'Enter the application number.' }]);
  }

  const recipient = input.recipient.trim() || app?.applicant?.ownerName?.trim() || app?.applicant?.name?.trim() || '';
  if (!recipient) throw badRequest('Name the recipient.', [{ path: 'recipient', message: 'Enter who it is addressed to.' }]);
  const address = input.address.trim() || app?.applicant?.ownerAddress?.trim() || app?.applicant?.address?.trim() || '';
  const documentReference =
    input.documentReference.trim() || (input.documentType === 'BPO' ? app?.approvalOrder?.orderNumber ?? '' : '');
  if (input.documentType === 'BPO' && !documentReference) {
    throw badRequest('This application has no building permission order to send.', [
      { path: 'documentReference', message: 'Enter the BPO number.' },
    ]);
  }

  return prisma.$transaction(
    (tx) =>
      createOutwardEntry(
        tx,
        {
          applicationId: app?.id ?? null,
          documentType: input.documentType,
          documentReference,
          sourceType: input.documentType === 'BPO' && app ? 'ApprovalOrder' : '',
          sourceId: '',
          subject: input.subject.trim() || `${documentReference || input.documentType}${app ? ` — ${app.applicationNumber}` : ''}`,
          recipient,
          address,
          status: input.readyForDispatch ? 'READY_FOR_DISPATCH' : 'DRAFT',
          remarks: input.remarks,
        },
        { actor: user, roleKey: user.roleKeys[0] ?? '', now: new Date(), meta }
      ),
    TX_LIMITS
  );
}

// ═══════════════════════════════════════════════════════════════════════════
// Moves
// ═══════════════════════════════════════════════════════════════════════════

const parseDay = (v: string | null | undefined, fallback: Date) => {
  if (!v) return fallback;
  const d = new Date(v.length === 10 ? `${v}T12:00:00` : v);
  return Number.isNaN(d.getTime()) ? fallback : d;
};

const AUDIT_ACTION: Record<OutwardAction, string> = {
  MARK_READY: 'OUTWARD_READY',
  DISPATCH: 'OUTWARD_DISPATCHED',
  RECORD_DELIVERY: 'OUTWARD_DELIVERED',
  RECORD_ACKNOWLEDGEMENT: 'OUTWARD_ACKNOWLEDGED',
  RECORD_RETURN: 'OUTWARD_RETURNED',
  CANCEL: 'OUTWARD_CANCELLED',
};

export async function outwardAction(user: AuthUser, id: string, input: OutwardActionInput, meta: Meta) {
  requireView(user);
  requireManage(user);
  const action = input.action as OutwardAction;
  const now = new Date();

  return prisma.$transaction(async (tx) => {
    const row = await tx.outwardEntry.findFirst({
      where: { id, ...scopeWhere(user) },
      select: { id: true, outwardNumber: true, status: true, applicationId: true, sourceType: true, sourceId: true, documentReference: true, dispatchDate: true, deliveredAt: true },
    });
    if (!row) throw notFound('That outward entry could not be found.');
    if (input.expectedStatus && input.expectedStatus !== row.status) {
      throw conflict(`This entry is now ${OUTWARD_STATUS_LABEL[row.status as OutwardStatus] ?? row.status}. Reload to see what changed.`, 'STALE_WRITE');
    }
    if (!canMoveOutward(action, row.status)) {
      throw conflict(`${OUTWARD_ACTION_LABEL[action]} is not possible on an entry that is ${OUTWARD_STATUS_LABEL[row.status as OutwardStatus] ?? row.status}.`);
    }

    const data: Prisma.OutwardEntryUpdateManyMutationInput = { status: OUTWARD_ACTION_RESULT[action] };
    const problems: Array<{ path: string; message: string }> = [];
    const future = (d: Date) => d.getTime() > now.getTime() + 60_000;

    if (action === 'DISPATCH') {
      if (!input.mode) problems.push({ path: 'mode', message: 'Choose how it is being sent.' });
      const when = parseDay(input.dispatchDate, now);
      if (future(when)) problems.push({ path: 'dispatchDate', message: 'The dispatch date cannot be in the future.' });
      if (input.mode && ['REGISTERED_POST', 'SPEED_POST', 'COURIER'].includes(input.mode) && !input.trackingNumber.trim()) {
        problems.push({ path: 'trackingNumber', message: 'Enter the tracking number for a posted or couriered item.' });
      }
      Object.assign(data, { mode: input.mode ?? '', dispatchDate: when, trackingNumber: input.trackingNumber.trim() });
    }
    if (action === 'RECORD_DELIVERY') {
      const when = parseDay(input.deliveredAt, now);
      if (future(when)) problems.push({ path: 'deliveredAt', message: 'The delivery date cannot be in the future.' });
      if (row.dispatchDate && when < new Date(row.dispatchDate.getTime() - 86_400_000)) {
        problems.push({ path: 'deliveredAt', message: 'Delivery cannot be before dispatch.' });
      }
      data.deliveredAt = when;
    }
    if (action === 'RECORD_ACKNOWLEDGEMENT') {
      if (!input.acknowledgement.trim()) problems.push({ path: 'acknowledgement', message: 'Say who acknowledged it, and how.' });
      const when = parseDay(input.acknowledgementDate, now);
      if (future(when)) problems.push({ path: 'acknowledgementDate', message: 'The acknowledgement date cannot be in the future.' });
      Object.assign(data, { acknowledgement: input.acknowledgement.trim(), acknowledgementDate: when });
      if (!row.deliveredAt) data.deliveredAt = when;
    }
    if (action === 'RECORD_RETURN') {
      if (!input.returnReason.trim()) problems.push({ path: 'returnReason', message: 'Say why it came back.' });
      Object.assign(data, { returnReason: input.returnReason.trim(), returnedAt: now });
    }
    if (action === 'CANCEL' && !input.remarks.trim()) problems.push({ path: 'remarks', message: 'Say why it is being cancelled.' });
    if (action === 'CANCEL' && GENERATED_SOURCES.includes(row.sourceType)) {
      problems.push({ path: 'action', message: 'A generated notice or order is not cancelled from Outward; it must be dispatched.' });
    }
    if (problems.length) throw badRequest('Some of the dispatch details are missing or not valid.', problems);
    if (input.remarks.trim()) data.remarks = input.remarks.trim();

    const { count } = await tx.outwardEntry.updateMany({ where: { id: row.id, status: row.status }, data });
    if (!count) throw conflict('Somebody else updated this entry just now. Reload to see what changed.', 'STALE_WRITE');

    const roleKey = user.roleKeys[0] ?? '';
    const to = OUTWARD_ACTION_RESULT[action];
    await tx.outwardEvent.create({
      data: {
        outwardId: row.id,
        action,
        fromStatus: row.status,
        toStatus: to,
        actorId: user.id,
        actorName: user.name,
        actorRoleKey: roleKey,
        remarks: [input.remarks.trim(), action === 'RECORD_RETURN' ? input.returnReason.trim() : '', action === 'RECORD_ACKNOWLEDGEMENT' ? input.acknowledgement.trim() : '']
          .filter(Boolean)
          .join(' — '),
        occurredAt: now,
      },
    });
    await audit(tx, {
      actor: user,
      action: AUDIT_ACTION[action],
      entityType: 'OutwardEntry',
      entityId: row.id,
      applicationId: row.applicationId,
      before: { status: row.status },
      after: {
        status: to,
        outwardNumber: row.outwardNumber,
        mode: data.mode ?? undefined,
        trackingNumber: data.trackingNumber ?? undefined,
        acknowledgement: data.acknowledgement ?? undefined,
      },
      remarks: input.remarks,
      ...meta,
    });

    // Dispatching a notice starts its response window.
    if (action === 'DISPATCH' && row.sourceType === 'ShowCauseNotice') {
      const moved = await tx.showCauseNotice.updateMany({
        where: { id: row.sourceId, status: 'ISSUED' },
        data: { status: 'AWAITING_RESPONSE' },
      });
      if (moved.count) {
        await tx.showCauseEvent.create({
          data: {
            showCauseId: row.sourceId,
            action: 'DISPATCHED',
            fromStatus: 'ISSUED',
            toStatus: 'AWAITING_RESPONSE',
            actorId: user.id,
            actorName: user.name,
            actorRoleKey: roleKey,
            remarks: `Dispatched as ${row.outwardNumber}${input.mode ? ` by ${input.mode.replace(/_/g, ' ').toLowerCase()}` : ''}.`,
            occurredAt: now,
          },
        });
        await audit(tx, {
          actor: user,
          action: 'SHOW_CAUSE_DISPATCHED',
          entityType: 'ShowCauseNotice',
          entityId: row.sourceId,
          applicationId: row.applicationId,
          before: { status: 'ISSUED' },
          after: { status: 'AWAITING_RESPONSE', outwardNumber: row.outwardNumber, noticeNumber: row.documentReference },
          ...meta,
        });
      }
    }

    return { id: row.id, outwardNumber: row.outwardNumber, status: to };
  }, TX_LIMITS);
}

// ═══════════════════════════════════════════════════════════════════════════
// Preview
// ═══════════════════════════════════════════════════════════════════════════

export async function readOutwardDocument(user: AuthUser, id: string): Promise<string> {
  requireView(user);
  const row = await requireEntry(user, id);
  if (row.sourceType === 'ShowCauseNotice' && row.sourceId) return readShowCauseNotice(user, row.sourceId);
  if (row.sourceType === 'RevocationProceeding' && row.sourceId) return readRevocationOrder(user, row.sourceId);
  return renderOutwardCover({
    outwardNumber: row.outwardNumber,
    documentType: row.documentType,
    documentReference: row.documentReference,
    subject: row.subject,
    applicationNumber: row.application?.applicationNumber ?? '',
    recipient: row.recipient,
    address: row.address,
    assignedDate: row.assignedDate,
    remarks: row.remarks,
  });
}
